[build]
  command = "remix build"
  functions = "netlify/functions"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

# [functions]
#   node_bundler = "esbuild"
#   external_node_modules = [
#     "@emotion/cache",
#     "@emotion/react",
#     "@emotion/server",
#     "@emotion/styled",
#     "@mdx-js/mdx",
#     "@mui/icons-material",
#     "@mui/lab",
#     "@mui/material",
#     "@netlify/functions",
#     "@remix-run/netlify",
#     "@remix-run/react",
#     "date-fns",
#     "draft-js",
#     "firebase",
#     "firebase-admin",
#     "firebase-functions",
#     "prism-react-renderer",
#     "react",
#     "react-dom",
#     "remix",
#     "tiny-invariant"
#   ]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
